spring:
  application:
    name: spring-cloud-eureka
  profiles: peer1

server:
  port: 1111

eureka:
  instance:
    hostname: peer1
  client:
    serviceUrl:
      defaultZone: http://peer2:1112/eureka,http://peer3:1113/eureka
    fetch-registry: true
    register-with-eureka: true
---
spring:
  application:
    name: spring-cloud-eureka
  profiles: peer2

server:
  port: 1112

eureka:
  instance:
    hostname: peer2
  client:
    serviceUrl:
      defaultZone: http://peer1:1111/eureka,http://peer3:1113/eureka
    fetch-registry: true
    register-with-eureka: true
---
spring:
  application:
    name: spring-cloud-eureka
  profiles: peer3

server:
  port: 1113

eureka:
  instance:
    hostname: peer3
  client:
    serviceUrl:
      defaultZone: http://peer2:1112/eureka,http://peer1:1111/eureka
    fetch-registry: true
    register-with-eureka: true